apiVersion: v1
kind: Pod
metadata:
  name: node-affinity
spec:
  affinity:
    nodeAffinity:
      # requiredDuringSchedulingIgnoredDuringExecution: # this is hard rule
      #   nodeSelectorTerms:
      #   - matchExpressions:
      #     - key: hardware
      #       operator: In
      #       values:
      #       # - gpu
      #         - gpuuu
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
            - key: hardware
              operator: In
              values:
              - gpuu
  containers:
  - name: node-affinity
    image: nginx