apiVersion: v1
kind: Pod
metadata:
  name: node-anti-affinity
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution: # this is soft rule
        - weight: 100 # High Weight (e.g., 90-100): "I really, really want this." ,,,,Low Weight (e.g., 1-10)
          preference:
            matchExpressions:
            - key: hardware
              operator: NotIn
              values:
              - gpu
  containers:
  - name: node-anti-affinity
    image: nginx